# Generated by Django 5.2 on 2025-04-25 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('enrollment_number', models.CharField(max_length=20, unique=True)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('skills', models.TextField(blank=True, help_text='Enter skills relevant to placements, comma-separated or one per line.')),
                ('projects', models.TextField(blank=True, help_text='Describe key academic or personal projects.')),
                ('resume_text', models.TextField(blank=True, help_text='Paste resume text or summarize key qualifications.')),
            ],
        ),
    ]
