# Generated by Django 5.2 on 2025-04-25 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the company', max_length=200, unique=True)),
                ('website', models.URLField(blank=True, help_text="Company's official website")),
                ('description', models.TextField(blank=True, help_text='Brief description of the company')),
                ('address', models.TextField(blank=True, help_text="Company's primary address (optional)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('role_type', models.CharField(choices=[('FT', 'Full-Time'), ('IN', 'Internship')], default='FT', max_length=2)),
                ('eligibility_criteria', models.TextField(blank=True, help_text='Mention required branch, CGPA cutoff, backlogs allowed, etc.')),
                ('package_details', models.CharField(blank=True, help_text="e.g., '15 LPA CTC' or '30,000/month stipend'", max_length=100)),
                ('application_deadline', models.DateTimeField(blank=True, help_text='Last date and time for students to apply', null=True)),
                ('drive_date', models.DateField(blank=True, help_text='Date when the drive process (e.g., test/interview) is scheduled', null=True)),
                ('status', models.CharField(choices=[('UP', 'Upcoming'), ('AC', 'Active'), ('CL', 'Closed')], default='UP', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='core.company')),
            ],
            options={
                'ordering': ['-application_deadline', 'company__name'],
            },
        ),
    ]
