# Generated by Django 5.2 on 2025-04-25 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_drive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AP', 'Applied'), ('SH', 'Shortlisted'), ('SL', 'Selected'), ('RJ', 'Rejected'), ('WD', 'Withdrawn')], default='AP', max_length=2)),
                ('tnp_comments', models.TextField(blank=True, help_text='Internal comments by TNP cell regarding this application (e.g., screening notes)')),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.drive')),
                ('student', models.ForeignKey(limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('student', 'drive')},
            },
        ),
    ]
